

table_options = {"frequent_sep": "----- Tablas especiales -----",
"tfm_industrial": "Producción industrial: total, sin refinería y núcleo (ene-02, M)",
 "tfm_prices": "Indicadores seleccionados de precios (mar-97, M)",
 "tfm_fiscal_gps_uyu_fssadj": "Cuentas fiscales: Sector público consolidado, ajustado FSS (ene-99, M)",
 "tfm_fiscal_nfps_uyu_fssadj": "Cuentas fiscales: Sector público no financiero, ajustado FSS (ene-99, M)",
 "tfm_fiscal_gc_uyu_fssadj": "Cuentas fiscales: Gobierno central-BPS, ajustado FSS (ene-99, M)",
 "tfm_pubdebt": "Deuda neta del sector público global excl. encajes (dic-99, T)",
 "tfm_labor_extended_nsa": "Mercado laboral: tasas y personas (ene-91, M)",
 "tfm_wages_nsa": "Mercado laboral: salarios nominales y reales (ene-68, M)",
 "tfm_tb": "Comercio internacional: balanza comercial por país (ene-00, M)",
 "tfm_tot": "Comercio internacional: términos de intercambio (ene-05, M)",
 "rxr_custom": "Tipos de cambio reales, cálculos econuy (dic-79, M)",
 "commodity_index": "Índice econuy de precios de materias primas (ene-02, M)",
 "activity_sep": "----- Actividad económica -----",
 "naccounts_gas_con_nsa": "Cuentas nacionales: Demanda, precios constantes, series armonizadas (mar-05, T)",
 "naccounts_ind_con_nsa": "Cuentas nacionales: Oferta, precios constantes, series armonizadas (mar-05, T)",
 "naccounts_ind_con_idx_nsa": "Cuentas nacionales: Oferta, índice real, series armonizadas (mar-97, T)",
 "naccounts_ind_con_idx_sa": "Cuentas nacionales: Oferta, índice real, series desestacionalizadas (mar-97, T)",
 "naccounts_ind_cur_nsa": "Cuentas nacionales: Oferta, precios corrientes, series armonizadas (mar-05, T)",
 "naccounts_gdp_cur_nsa": "Cuentas nacionales: PBI, precios corrientes (mar-97, T)",
 "industrial_production": "Producción industrial: por división, agrupaciones y clases (ene-02, M)",
 "prices_sep": "----- Precios -----",
 "cpi": "Índice de precios al consumidor (ene-37, M)",
 "nxr_monthly": "Tipo de cambio, interbancario, mensual (abr-72, M)",
 "nxr_daily": "Tipo de cambio, interbancario, diario (3-ene-00, D)",
 "fiscal_sep": "----- Cuentas fiscales -----",
 "fiscal_nfps": "Cuentas fiscales: Sector público no financiero (ene-99, M)",
 "fiscal_gps": "Cuentas fiscales: Sector público consolidado (ene-99, M)",
 "fiscal_gc-bps": "Cuentas fiscales: Gobierno central-BPS (ene-99, M)",
 "fiscal_ancap": "Cuentas fiscales: ANCAP (ene-01, M)",
 "fiscal_antel": "Cuentas fiscales: ANTEL (ene-99, M)",
 "fiscal_ose": "Cuentas fiscales: OSE (ene-99, M)",
 "fiscal_ute": "Cuentas fiscales: UTE (ene-99, M)",
 "public_debt_gps": "Deuda del sector público global: por plazo contractual, plazo residual, moneda y residencia (dic-99, T)",
 "public_debt_nfps": "Deuda del sector público no monetario: por plazo contractual, plazo residual, moneda y residencia (dic-99, T)",
 "public_debt_cb": "Deuda del Banco Central: por plazo contractual, plazo residual, moneda y residencia (dic-99, T)",
 "labor_sep": "----- Mercado laboral -----",
 "labor": "Mercado laboral: tasas de actividad, empleo y desempleo (ene-06, M)",
 "wages": "Mercado laboral: salarios (ene-68, M)",
 "external_sep": "----- Sector externo -----",
 "tb_x_prod_val": "Comercio internacional: Exportaciones por sector, valor (ene-00, M)",
 "tb_x_prod_vol": "Comercio internacional: Exportaciones por sector, volumen (ene-05, M)",
 "tb_x_prod_pri": "Comercio internacional: Exportaciones por sector, precio (ene-05, M)",
 "tb_x_dest_val": "Comercio internacional: Exportaciones por destino, valor (ene-00, M)",
 "tb_x_dest_vol": "Comercio internacional: Exportaciones por destino, volumen (ene-05, M)",
 "tb_x_dest_pri": "Comercio internacional: Exportaciones por destino, precio (ene-05, M)",
 "tb_m_sect_val": "Comercio internacional: Importaciones por tipo, valor (ene-00, M)",
 "tb_m_sect_vol": "Comercio internacional: Importaciones por tipo, volumen (ene-05, M)",
 "tb_m_sect_pri": "Comercio internacional: Importaciones por tipo, precio (ene-05, M)",
 "tb_m_orig_val": "Comercio internacional: Importaciones por origen, valor (ene-00, M)",
 "tb_m_orig_vol": "Comercio internacional: Importaciones por origen, volumen (ene-05, M)",
 "tb_m_orig_pri": "Comercio internacional: Importaciones por origen, precio (ene-05, M)",
 "rxr_official": "Tipos de cambio reales, BCU (ene-00, M)",
 "money_sep": "----- Moneda y banca -----",
 "reserves": "Reservas internacionales (26-jun-02, D)",
 "reserves_chg": "Variación en las reservas del BCU (2-ene-13, D)"}