table_options = {
    "activity_sep": "----- Actividad económica -----",
    "naccounts_gas_con_nsa": "Cuentas nacionales: Demanda, precios constantes, series armonizadas (mar-05, T)",
    "naccounts_ind_con_nsa": "Cuentas nacionales: Oferta, precios constantes, series armonizadas (mar-05, T)",
    "naccounts_ind_con_idx_nsa": "Cuentas nacionales: Oferta, índice real, series armonizadas (mar-97, T)",
    "naccounts_ind_con_idx_sa": "Cuentas nacionales: Oferta, índice real, series desestacionalizadas (mar-97, T)",
    "naccounts_ind_cur_nsa": "Cuentas nacionales: Oferta, precios corrientes, series armonizadas (mar-05, T)",
    "naccounts_gdp_cur_nsa": "Cuentas nacionales: PBI, precios corrientes (mar-97, T)",
    "industrial_production": "Producción industrial: por división, agrupaciones y clases (ene-02, M)",
    "electricity": "Ventas de energía eléctrica por sector (ene-00, M)",
    "gasoline": "Ventas de nafta por departamento (ene-04, M)",
    "diesel": "Ventas de gasoil por departamento (ene-04, M)",
    "cattle": "Faena de bovinos (2-ene-05, S)",
    "milk": "Remisión de leche a planta (ene-02, M)",
    "cement": "Ventas de cemento (ene-90, M)",
    "core_industrial": "Producción industrial: total, sin refinería y núcleo (ene-02, M [e])",
    "prices_sep": "----- Precios -----",
    "cpi": "Índice de precios al consumidor - IPC (ene-37, M)",
    "cpi_measures": "Indicadores seleccionados de precios (mar-97, M [e])",
    "nxr_monthly": "Tipo de cambio, interbancario, mensual (abr-72, M)",
    "nxr_daily": "Tipo de cambio, interbancario, diario (3-ene-00, D)",
    "fiscal_sep": "----- Cuentas fiscales -----",
    "balance_nfps": "Resultado fiscal: Sector público no financiero (ene-99, M)",
    "balance_gps": "Resultado fiscal: Sector público consolidado (ene-99, M)",
    "balance_gc-bps": "Resultado fiscal: Gobierno central-BPS (ene-99, M)",
    "balance_ancap": "Resultado fiscal: ANCAP (ene-01, M)",
    "balance_antel": "Resultado fiscal: ANTEL (ene-99, M)",
    "balance_ose": "Resultado fiscal: OSE (ene-99, M)",
    "balance_ute": "Resultado fiscal: UTE (ene-99, M)",
    "balance_fss_gps_fssadj": "Resultado fiscal: Sector público consolidado, ajustado FSS (ene-99, M [e])",
    "balance_fss_nfps_fssadj": "Resultado fiscal: Sector público no financiero, ajustado FSS (ene-99, M [e])",
    "balance_fss_gc_fssadj": "Resultado fiscal: Gobierno central-BPS, ajustado FSS (ene-99, M [e])",
    "taxes": "Recaudación impositiva (ene-82, M)",
    "public_debt_gps": "Deuda del sector público global: por plazo contractual, plazo residual, moneda y residencia (dic-99, T)",
    "public_debt_nfps": "Deuda del sector público no monetario: por plazo contractual, plazo residual, moneda y residencia (dic-99, T)",
    "public_debt_cb": "Deuda del Banco Central: por plazo contractual, plazo residual, moneda y residencia (dic-99, T)",
    "net_public_debt": "Deuda neta del sector público global excl. encajes (dic-99, T [e])",
    "labor_sep": "----- Mercado laboral -----",
    "labor": "Tasas de actividad, empleo y desempleo (ene-06, M)",
    "rates_people": "Actividad, empleo y desempleo: series extendidas de tasas y personas (ene-91, M [e])",
    "hours": "Horas promedio trabajadas por sector (ene-06, M)",
    "nominal_wages": "Salarios nominales: total, públicos y privados (ene-68, M)",
    "real_wages": "Salarios reales: total, públicos y privados (ene-68, M)",
    "external_sep": "----- Sector externo -----",
    "trade_x_prod_val": "Exportaciones por sector, valor (ene-00, M)",
    "trade_x_prod_vol": "Exportaciones por sector, volumen (ene-05, M)",
    "trade_x_prod_pri": "Exportaciones por sector, precio (ene-05, M)",
    "trade_x_dest_val": "Exportaciones por destino, valor (ene-00, M)",
    "trade_x_dest_vol": "Exportaciones por destino, volumen (ene-05, M)",
    "trade_x_dest_pri": "Exportaciones por destino, precio (ene-05, M)",
    "trade_m_sect_val": "Importaciones por tipo, valor (ene-00, M)",
    "trade_m_sect_vol": "Importaciones por tipo, volumen (ene-05, M)",
    "trade_m_sect_pri": "Importaciones por tipo, precio (ene-05, M)",
    "trade_m_orig_val": "Importaciones por origen, valor (ene-00, M)",
    "trade_m_orig_vol": "Importaciones por origen, volumen (ene-05, M)",
    "trade_m_orig_pri": "Importaciones por origen, precio (ene-05, M)",
    "net_trade": "Balanza comercial por país (ene-00, M [e])",
    "terms_of_trade": "Términos de intercambio (ene-05, M [e])",
    "commodity_index": "Índice econuy de precios de materias primas (ene-02, M [e])",
    "containers": "Movimiento de contenedores en el Puerto de Montevideo (ene-07, M)",
    "rxr_official": "Tipos de cambio reales, BCU (ene-00, M)",
    "rxr_custom": "Tipos de cambio reales, cálculos econuy (dic-79, M [e])",
    "reserves": "Reservas internacionales (26-jun-02, D)",
    "reserves_changes": "Variación en las reservas del BCU (2-ene-13, D)",
    "financial_sep": "----- Sector financiero -----",
    "deposits": "Depósitos en el sistema bancario (dic-98, M)",
    "credit": "Créditos del sistema bancario al sector no financiero (dic-98, M)",
    "interest_rates": "Tasas de interés activas y pasivas (ene-98, M)",
    "call": "Tasa call a 1 día (02-ene-02, D)",
    "bonds": "Rendimiento de bonos soberanos (02-jun-03, D [e])",
    "sovereign_risk": "Uruguay Bond Index - riesgo soberano (01-ene-1999, D)",
    "income_sep": "----- Ingresos -----",
    "household_income": "Ingreso medio de los hogares sin valor ni aguinaldo (ene-06, M)",
    "capita_income": "Ingreso medio per cápita sin valor locativo ni aguinaldo (ene-06, M)",
    "consumer_confidence": "Índice de Confianza del Consumidor (ago-07, M)"
}
